/**
 * Thin Cloudflare entry in front of the OpenNext worker.
 *
 * Free-tier Workers get ~10ms of CPU per invocation. Importing the OpenNext
 * handler evaluates Next.js and Clerk, which is why `/robots.txt` and
 * `/wp-login.php` were burning hundreds of milliseconds. This file answers
 * those requests first and only dynamically imports `.open-next/worker.js`
 * for real application routes. Keep that import dynamic — a top-level import
 * pulls the whole server into startup.
 *
 * `.open-next/worker.js` is created by `opennextjs-cloudflare build`.
 */
import {
  classifyPath,
  isCacheablePublicDocument,
  productionClerkKeyWarning,
  PUBLIC_HTML_CACHE_SECONDS,
} from "./lib/edge-routes";

interface AssetFetcher {
  fetch(request: Request): Promise<Response>;
}

interface WorkerEnv {
  ASSETS?: AssetFetcher;
  CLERK_SECRET_KEY?: string;
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY?: string;
}

interface WorkerContext {
  waitUntil(promise: Promise<unknown>): void;
}

interface OpenNextWorker {
  fetch(
    request: Request,
    env: WorkerEnv,
    ctx: WorkerContext,
  ): Promise<Response> | Response;
}

const METADATA_CACHE_CONTROL = "public, max-age=86400";
const PROBE_CACHE_CONTROL = "public, max-age=86400";

let didCheckProductionClerkKeys = false;

function textResponse(
  body: string,
  status: number,
  headers: Record<string, string>,
): Response {
  return new Response(body, {
    status,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "x-content-type-options": "nosniff",
      ...headers,
    },
  });
}

function getEdgeCache(): Cache | undefined {
  const caches = (globalThis as { caches?: { default?: Cache } }).caches;
  return caches?.default;
}

function publicHtmlCacheKey(url: URL): Request {
  return new Request(new URL("/", url.origin).toString(), { method: "GET" });
}

async function fetchStaticAsset(
  env: WorkerEnv,
  pathname: string,
): Promise<Response | undefined> {
  if (!env.ASSETS) return undefined;

  try {
    const assetUrl = new URL(pathname, "https://assets.local");
    const response = await env.ASSETS.fetch(new Request(assetUrl));
    if (response.status === 404) return undefined;
    return response;
  } catch {
    return undefined;
  }
}

async function loadOpenNextWorker(): Promise<OpenNextWorker> {
  // @ts-expect-error Generated by `opennextjs-cloudflare build` before deploy.
  const loaded = await import("./.open-next/worker.js");
  return loaded.default as OpenNextWorker;
}

function warnIfProductionUsesDevelopmentClerkKeys(
  request: Request,
  env: WorkerEnv,
) {
  if (didCheckProductionClerkKeys) return;

  const hostname = new URL(request.url).hostname.toLowerCase();
  if (hostname !== "readiumx.com" && hostname !== "www.readiumx.com") return;

  didCheckProductionClerkKeys = true;
  const warning = productionClerkKeyWarning({
    hostname,
    secretKey: env.CLERK_SECRET_KEY,
    publishableKey: env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  });
  if (warning) console.warn(warning);
}

async function fetchApplication(
  request: Request,
  env: WorkerEnv,
  ctx: WorkerContext,
  url: URL,
): Promise<Response> {
  warnIfProductionUsesDevelopmentClerkKeys(request, env);

  const openNext = await loadOpenNextWorker();
  const response = await openNext.fetch(request, env, ctx);
  if (!isCacheablePublicDocument(request.method, url, request.headers)) {
    return response;
  }
  if (response.status !== 200) return response;
  if (response.headers.has("set-cookie")) return response;

  const contentType = response.headers.get("content-type") ?? "";
  if (!contentType.includes("text/html")) return response;

  const headers = new Headers(response.headers);
  headers.set(
    "cache-control",
    `public, max-age=60, s-maxage=${PUBLIC_HTML_CACHE_SECONDS}`,
  );
  headers.set("x-readium-cache", "miss");

  const cached = new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
  const cache = getEdgeCache();
  if (cache) {
    ctx.waitUntil(cache.put(publicHtmlCacheKey(url), cached.clone()));
  }
  return cached;
}

const worker = {
  async fetch(
    request: Request,
    env: WorkerEnv,
    ctx: WorkerContext,
  ): Promise<Response> {
    const url = new URL(request.url);
    const classified = classifyPath(url.pathname);

    if (classified.type === "probe") {
      return textResponse("Not Found", 404, {
        "cache-control": PROBE_CACHE_CONTROL,
      });
    }

    if (classified.type === "metadata") {
      if (request.method !== "GET" && request.method !== "HEAD") {
        return textResponse("Method Not Allowed", 405, {
          allow: "GET, HEAD",
        });
      }

      return new Response(request.method === "HEAD" ? null : classified.body, {
        status: 200,
        headers: {
          "content-type": classified.contentType,
          "cache-control": METADATA_CACHE_CONTROL,
          "x-content-type-options": "nosniff",
        },
      });
    }

    if (classified.type === "static-asset") {
      const asset = await fetchStaticAsset(env, url.pathname);
      if (asset) return asset;
      return textResponse("Not Found", 404, {
        "cache-control": PROBE_CACHE_CONTROL,
      });
    }

    if (isCacheablePublicDocument(request.method, url, request.headers)) {
      const cache = getEdgeCache();
      const hit = cache
        ? await cache.match(publicHtmlCacheKey(url))
        : undefined;
      if (hit) {
        const headers = new Headers(hit.headers);
        headers.set("x-readium-cache", "hit");
        return new Response(hit.body, {
          status: hit.status,
          statusText: hit.statusText,
          headers,
        });
      }
    }

    return fetchApplication(request, env, ctx, url);
  },
};

export default worker;
